### PR TITLE
add support for Float64Arrays, increase performance

### PR DESCRIPTION
**Pull request by philippsimon**
add support for Float64Arrays, increase performance by removing not needed copy of values (210ms => 40ms for 1000000 values)

### CODE REVIEW

**Comment by rfink** [comment]
Thanks for taking the time to make improvements to the library.  I like almost all the changes here, but I think forcing Float64Arrays would break compatibility with older browsers.  Maybe it makes sense to just have it support Float64Arrays, without enforcing them?

**Comment by philippsimon** [comment]
You're welcome. And it doesn't enforce the user to use Float64Arrays. I didn't change your tests and they were all made with normal arrays and they all pass the tests like before.

**Comment by rfink** [comment]
Ah, I see.  Those 2 lines that check for arrays are a bit visually confusing.  Can you add a curly brace and indentation there?  Other than that, I saw you removed the dependency on underscore, but not the require.  If those few things are taken care of, I think we're good to merge.  Thanks again.

**Comment by philippsimon** [comment]
I removed the dependency and cleaned up my code. Also I converted the code to TypeScript to make it nicer to use in other projects and added also more JSDoc3 comments (@params and @returns).
In general I would suggest to add also travis to the project to see directly if the request passes the tests. Like i.e. here: https://github.com/gruntjs/grunt-contrib-compress

**Comment by philippsimon** [comment]
@rfink so what do you think? Is it a too drastic change for you?

**Comment by rfink** [comment]
I apologize for not being more attentive, I've been in a bit of a crunch at work.  I think the only thing I'm not crazy about is TypeScript, since I'm very unfamiliar with it, and therefore am unfit to maintain it.  I like the rest of the changes, however.  It might make sense to maintain a separate project for the TS version, maybe not.  What are your thoughts?

**Comment by philippsimon** [comment]
no problem - I have the same problem at the moment ;) I only played around with polyfit and optimized it to compare the performance between Matlab, numpy and Node.js and one function I compared was polyfit (it was faster then Matlab and numpy!! but in the end I decided to move from Matlab to numpy).
And yes I know it's quite a big change. I also don't have no good idea how to solve it. As I don't like to separate the projects there would be 2 ways:
1. Leave the TypeScript file inside and when you update the JavaScript version, I just update the TypeScript file accordingly. Like that it's easier to integrate the library in TypeScript projects.
2. Have a second TypeScript branch. It's just cleaner and when you add in the ReadMe a note that there is also a TypeScript version it would be also fine. Maybe we can just add to the tag somethink like -ts (I don't know what is allowed there).

What do you think?

**Comment by rfink** [comment]
I'll go ahead and leave the TS file in there.  The module has been fairly low maintenance so far, and maybe it's about time I learn TS finally.  I'll get this merged in, tagged and released by the end of the weekend.  Thanks very much for the contributions.

**Comment by philippsimon** [comment]
You're very welcome. I cleaned up now also a bit more my TypeScript code.

In general it would be also great if this library would be integrated in [scijs](http://scijs.net/packages/#scijs/).

**Comment by rfink** [comment]
Merged and tagged as v0.1.0.  Thanks for all your contributions, again.  I would be honored for it to be featured in scijs, but I don't know those guys, so I don't have any reason to believe it would.

**Pull request merged**
